/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices/$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedManagersIndexRouteImport } from './routes/_authenticated/managers/index'
import { Route as AuthenticatedManagersIdRouteImport } from './routes/_authenticated/managers/$id'
import { Route as AuthenticatedPayoutsIndexRouteImport } from './routes/_authenticated/payouts/index'
import { Route as AuthenticatedPayoutsIdRouteImport } from './routes/_authenticated/payouts/$id'
import { Route as AuthenticatedPayoutsNewRouteImport } from './routes/_authenticated/payouts/new'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedServicesIdRouteImport } from './routes/_authenticated/services/$id'
import { Route as AuthenticatedWorkersIndexRouteImport } from './routes/_authenticated/workers/index'
import { Route as AuthenticatedWorkersIdRouteImport } from './routes/_authenticated/workers/$id'
import { Route as AuthenticatedInvoicesIdEditRouteImport } from './routes/_authenticated/invoices/$id_.edit'
import { Route as AuthenticatedPayoutsIdEditRouteImport } from './routes/_authenticated/payouts/$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagersIndexRoute =
  AuthenticatedManagersIndexRouteImport.update({
    id: '/managers/',
    path: '/managers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagersIdRoute = AuthenticatedManagersIdRouteImport.update({
  id: '/managers/$id',
  path: '/managers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsIndexRoute =
  AuthenticatedPayoutsIndexRouteImport.update({
    id: '/payouts/',
    path: '/payouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayoutsIdRoute = AuthenticatedPayoutsIdRouteImport.update({
  id: '/payouts/$id',
  path: '/payouts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsNewRoute = AuthenticatedPayoutsNewRouteImport.update({
  id: '/payouts/new',
  path: '/payouts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesIdRoute = AuthenticatedServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkersIndexRoute =
  AuthenticatedWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersIdRoute = AuthenticatedWorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesIdEditRoute =
  AuthenticatedInvoicesIdEditRouteImport.update({
    id: '/invoices/$id_/edit',
    path: '/invoices/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayoutsIdEditRoute =
  AuthenticatedPayoutsIdEditRouteImport.update({
    id: '/payouts/$id_/edit',
    path: '/payouts/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/managers/$id': typeof AuthenticatedManagersIdRoute
  '/payouts/$id': typeof AuthenticatedPayoutsIdRoute
  '/payouts/new': typeof AuthenticatedPayoutsNewRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/workers/$id': typeof AuthenticatedWorkersIdRoute
  '/managers/': typeof AuthenticatedManagersIndexRoute
  '/payouts/': typeof AuthenticatedPayoutsIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/workers/': typeof AuthenticatedWorkersIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/payouts/$id/edit': typeof AuthenticatedPayoutsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/managers/$id': typeof AuthenticatedManagersIdRoute
  '/payouts/$id': typeof AuthenticatedPayoutsIdRoute
  '/payouts/new': typeof AuthenticatedPayoutsNewRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/workers/$id': typeof AuthenticatedWorkersIdRoute
  '/managers': typeof AuthenticatedManagersIndexRoute
  '/payouts': typeof AuthenticatedPayoutsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/workers': typeof AuthenticatedWorkersIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/payouts/$id/edit': typeof AuthenticatedPayoutsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/managers/$id': typeof AuthenticatedManagersIdRoute
  '/_authenticated/payouts/$id': typeof AuthenticatedPayoutsIdRoute
  '/_authenticated/payouts/new': typeof AuthenticatedPayoutsNewRoute
  '/_authenticated/services/$id': typeof AuthenticatedServicesIdRoute
  '/_authenticated/workers/$id': typeof AuthenticatedWorkersIdRoute
  '/_authenticated/managers/': typeof AuthenticatedManagersIndexRoute
  '/_authenticated/payouts/': typeof AuthenticatedPayoutsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/workers/': typeof AuthenticatedWorkersIndexRoute
  '/_authenticated/invoices/$id_/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/_authenticated/payouts/$id_/edit': typeof AuthenticatedPayoutsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/managers/$id'
    | '/payouts/$id'
    | '/payouts/new'
    | '/services/$id'
    | '/workers/$id'
    | '/managers/'
    | '/payouts/'
    | '/services/'
    | '/workers/'
    | '/invoices/$id/edit'
    | '/payouts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/managers/$id'
    | '/payouts/$id'
    | '/payouts/new'
    | '/services/$id'
    | '/workers/$id'
    | '/managers'
    | '/payouts'
    | '/services'
    | '/workers'
    | '/invoices/$id/edit'
    | '/payouts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/managers/$id'
    | '/_authenticated/payouts/$id'
    | '/_authenticated/payouts/new'
    | '/_authenticated/services/$id'
    | '/_authenticated/workers/$id'
    | '/_authenticated/managers/'
    | '/_authenticated/payouts/'
    | '/_authenticated/services/'
    | '/_authenticated/workers/'
    | '/_authenticated/invoices/$id_/edit'
    | '/_authenticated/payouts/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/managers/': {
      id: '/_authenticated/managers/'
      path: '/managers'
      fullPath: '/managers/'
      preLoaderRoute: typeof AuthenticatedManagersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/managers/$id': {
      id: '/_authenticated/managers/$id'
      path: '/managers/$id'
      fullPath: '/managers/$id'
      preLoaderRoute: typeof AuthenticatedManagersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts/': {
      id: '/_authenticated/payouts/'
      path: '/payouts'
      fullPath: '/payouts/'
      preLoaderRoute: typeof AuthenticatedPayoutsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts/$id': {
      id: '/_authenticated/payouts/$id'
      path: '/payouts/$id'
      fullPath: '/payouts/$id'
      preLoaderRoute: typeof AuthenticatedPayoutsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts/new': {
      id: '/_authenticated/payouts/new'
      path: '/payouts/new'
      fullPath: '/payouts/new'
      preLoaderRoute: typeof AuthenticatedPayoutsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/$id': {
      id: '/_authenticated/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthenticatedServicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/': {
      id: '/_authenticated/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AuthenticatedWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/$id': {
      id: '/_authenticated/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof AuthenticatedWorkersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id_/edit': {
      id: '/_authenticated/invoices/$id_/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts/$id_/edit': {
      id: '/_authenticated/payouts/$id_/edit'
      path: '/payouts/$id/edit'
      fullPath: '/payouts/$id/edit'
      preLoaderRoute: typeof AuthenticatedPayoutsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedManagersIdRoute: typeof AuthenticatedManagersIdRoute
  AuthenticatedPayoutsIdRoute: typeof AuthenticatedPayoutsIdRoute
  AuthenticatedPayoutsNewRoute: typeof AuthenticatedPayoutsNewRoute
  AuthenticatedServicesIdRoute: typeof AuthenticatedServicesIdRoute
  AuthenticatedWorkersIdRoute: typeof AuthenticatedWorkersIdRoute
  AuthenticatedManagersIndexRoute: typeof AuthenticatedManagersIndexRoute
  AuthenticatedPayoutsIndexRoute: typeof AuthenticatedPayoutsIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedWorkersIndexRoute: typeof AuthenticatedWorkersIndexRoute
  AuthenticatedInvoicesIdEditRoute: typeof AuthenticatedInvoicesIdEditRoute
  AuthenticatedPayoutsIdEditRoute: typeof AuthenticatedPayoutsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedManagersIdRoute: AuthenticatedManagersIdRoute,
  AuthenticatedPayoutsIdRoute: AuthenticatedPayoutsIdRoute,
  AuthenticatedPayoutsNewRoute: AuthenticatedPayoutsNewRoute,
  AuthenticatedServicesIdRoute: AuthenticatedServicesIdRoute,
  AuthenticatedWorkersIdRoute: AuthenticatedWorkersIdRoute,
  AuthenticatedManagersIndexRoute: AuthenticatedManagersIndexRoute,
  AuthenticatedPayoutsIndexRoute: AuthenticatedPayoutsIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedWorkersIndexRoute: AuthenticatedWorkersIndexRoute,
  AuthenticatedInvoicesIdEditRoute: AuthenticatedInvoicesIdEditRoute,
  AuthenticatedPayoutsIdEditRoute: AuthenticatedPayoutsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
